server {
    listen 80;

    # фронтенд
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }

    # backend admin-panel
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
    }

    # платформа (если запущена отдельно)
    location /platform/ {
        rewrite ^/platform(/.*)$ $1 break;
        proxy_pass http://host.docker.internal:8000/;
        proxy_set_header Host $host;
    }
}
